### ISSUE TITLE
"don't work for SPDX v2.2"

### ISSUE THREAD

**Issue by zvr** [spdx/tools-python#196] opened 2021-10-20 14:14 UTC
On https://github.com/intel/cve-bin-tool/issues/1382, @anthonyharrison writes:

>  I am aware of these tools but when I looked at them they didn't work for SPDX v2.2 files (certainly the version in PyPi).

and mentions the test files in https://github.com/spdx/spdx-spec/tree/development/v2.2.2/examples

Is this correct?

**Comment by dholth** [comment] 2021-11-16 16:16
Serializing 2.2 per the jsonschema at https://github.com/spdx/tools-python/pull/197

**Comment by nettrino** [comment] 2022-07-27 08:21
Related to @anthonyharrison's comment above - would it make sense to automatically use https://github.com/spdx/spdx-spec/tree/master/examples automatically in tests? currently the master branch examples (e.g., https://github.com/spdx/spdx-spec/blob/master/examples/SPDXJSONExample-v2.2.spdx.json)  also fail using the `JSONParser` for me

**Comment by meretp** [comment] 2022-11-07 13:55
#211 is a duplicate of this issue resp. a subproblem of this one. As commented in the other issue I tried to analyze the errors described by @anthonyharrison but couldn't fix them yet: 
> 
> I had a deeper look at the errors you provided. The first one is rather misleading, it is thrown by the tagvalue parser [here](https://github.com/spdx/tools-python/blob/30c1f4ea2e5782bf8cacea67a7febfa19cae6c92/spdx/parsers/tagvalue.py#L1322-L1326) because the lexer couldn't parse the given line. The error message should be adjusted here. As far as I understand the error is produced [here](https://github.com/spdx/tools-python/blob/30c1f4ea2e5782bf8cacea67a7febfa19cae6c92/spdx/parsers/lexers/tagvalue.py#L105) but I don't know yet how to fix this.
> 
> Concerning the second error: The current tagvalue-parser expects the ordering of a SPDX-Document so that the packages are placed first and the files come afterwards. The parsing of some fields is based on this ordering, e.g. [here](https://github.com/spdx/tools-python/blob/30c1f4ea2e5782bf8cacea67a7febfa19cae6c92/spdx/parsers/tagvalue.py#L562-L570). This also needs a deeper understanding of the tagvalue-parser.
> 
> As discussed in #244 we will soon refactor the whole data model and the builder/ parser-structure. In this context we will then also take care of the errors described here.


I would agree with @nettrino that it would be best to use the examples from the spec for the tests.

**Comment by meretp** [comment] 2022-11-28 16:15
I would close this issue for now as the described errors for tag-value files are fixed and all example files for version 2.2 except the rdf example from the spec repo can be parsed now. Concerning the rdf file I opened another issue (#323) which is more specific than this one. If anyone has any objections, please ping and/or reopen.

**Closed by meretp** 2022-11-28 16:15 UTC
Labels: SPDX v2.2
