### ISSUE TITLE
Does the tool have support for converting SPDX 2.2 tag files?

### ISSUE THREAD

**Issue by makdataproj** [spdx/tools-python#211] opened 2022-04-06 16:44 UTC
Getting this error when trying to convert SPDX 2.2 tag file to SPDX 2.2 json file: 

data:AnnotationType must be "REVIEW" or "OTHER". Line: 23

data:FileName Can not appear before PackageName, line: 41

**Comment by meretp** [comment] 2022-11-07 13:17
Hi @makdataproj! Thanks for your issue, to answer your initial question:  Unfortunately the tool doesn't fully support spec version 2.2 but we are currently working on it. 

I had a deeper look at the errors you provided.
The first one is rather misleading, it is thrown by the tagvalue parser [here](https://github.com/spdx/tools-python/blob/30c1f4ea2e5782bf8cacea67a7febfa19cae6c92/spdx/parsers/tagvalue.py#L1322-L1326) because the lexer couldn't parse the given line. The error message should be adjusted here. As far as I understand the error is produced [here](https://github.com/spdx/tools-python/blob/30c1f4ea2e5782bf8cacea67a7febfa19cae6c92/spdx/parsers/lexers/tagvalue.py#L105) but I don't know yet how to fix this.

Concerning the second error: The current tagvalue-parser expects the ordering of a SPDX-Document so that the packages are placed first and the files come afterwards. The parsing of some fields is based on this ordering, e.g. [here](https://github.com/spdx/tools-python/blob/30c1f4ea2e5782bf8cacea67a7febfa19cae6c92/spdx/parsers/tagvalue.py#L562-L570). This also needs a deeper understanding of the tagvalue-parser. 

As discussed in #244 we will soon refactor the whole data model and the builder/ parser-structure. In this context we will then also take care of the errors described here.

**Comment by meretp** [comment] 2022-11-07 13:56
As this is a duplicate of #196 I will close this issue for now.

**Closed by meretp** 2022-11-07 13:56 UTC
Labels: SPDX v2.2
